# Site settings
title: Pousse-Café Framework
email: info@pousse-cafe-framework.org
description: >
  Pousse-Café is a framework assisting you in writing applications following Domain Driven Design methodology. While DDD
  has proven to be useful in writing code representing complex business rules and/or having strong scalability requirements,
  it is not always easy to apply given the number of transversal issues that need to be addressed. Pousse-Café's purpose
  is to solve most of those issues allowing developers to focus on the Domain and its implementation.
baseurl: ""
url: http://www.pousse-cafe-framework.org
latest_release_version: 0.1.0

# Build settings
markdown: kramdown
